version: '3.8'

services:
  # pgAdmin for PostgreSQL Management (Standalone)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tradebot-pgadmin-standalone
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tradebot-network

volumes:
  pgadmin_data:
    driver: local

networks:
  tradebot-network:
    driver: bridge
