"""Add leverage column to bot_configs

Revision ID: 107856acfca7
Revises: 3742c83cd3b1
Create Date: 2025-05-25 21:14:06.603305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107856acfca7'
down_revision: Union[str, None] = '3742c83cd3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('leverage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'leverage')
    # ### end Alembic commands ###
