"""create_bot_config_table

Revision ID: 19adfce0d2a6
Revises: 4b2e65b4c85b
Create Date: 2025-05-23 02:02:38.311059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19adfce0d2a6'
down_revision: Union[str, None] = '4b2e65b4c85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('initial_capital', sa.Numeric(), nullable=True),
    sa.Column('daily_target_perc', sa.Numeric(), nullable=True),
    sa.Column('max_daily_loss_perc', sa.Numeric(), nullable=True),
    sa.Column('position_size_perc', sa.Numeric(), nullable=True),
    sa.Column('position_size_fixed', sa.Numeric(), nullable=True),
    sa.Column('stop_loss_perc', sa.Numeric(), nullable=False),
    sa.Column('take_profit_perc', sa.Numeric(), nullable=False),
    sa.Column('trailing_stop_perc', sa.Numeric(), nullable=True),
    sa.Column('trailing_stop_active', sa.Boolean(), nullable=True),
    sa.Column('ema_fast', sa.Integer(), nullable=False),
    sa.Column('ema_slow', sa.Integer(), nullable=False),
    sa.Column('rsi_period', sa.Integer(), nullable=False),
    sa.Column('rsi_oversold', sa.Integer(), nullable=False),
    sa.Column('rsi_overbought', sa.Integer(), nullable=False),
    sa.Column('max_daily_trades', sa.Integer(), nullable=True),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_id'), 'bot_configs', ['id'], unique=False)
    op.create_index(op.f('ix_bot_configs_user_id'), 'bot_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_configs_user_id'), table_name='bot_configs')
    op.drop_index(op.f('ix_bot_configs_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    # ### end Alembic commands ###
