"""add_advanced_bot_parameters

Revision ID: 3742c83cd3b1
Revises: 92c67f02186c
Create Date: 2025-05-24 14:21:28.342977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3742c83cd3b1'
down_revision: Union[str, None] = '92c67f02186c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('custom_ema_fast', sa.Integer(), nullable=True))
    op.add_column('bot_configs', sa.Column('custom_ema_slow', sa.Integer(), nullable=True))
    op.add_column('bot_configs', sa.Column('custom_rsi_period', sa.Integer(), nullable=True))
    op.add_column('bot_configs', sa.Column('custom_rsi_oversold', sa.Integer(), nullable=True))
    op.add_column('bot_configs', sa.Column('custom_rsi_overbought', sa.Integer(), nullable=True))
    op.add_column('bot_configs', sa.Column('custom_stop_loss', sa.Numeric(), nullable=True))
    op.add_column('bot_configs', sa.Column('custom_take_profit', sa.Numeric(), nullable=True))
    op.add_column('bot_configs', sa.Column('custom_trailing_stop', sa.Numeric(), nullable=True))
    op.add_column('bot_configs', sa.Column('position_type', sa.String(), nullable=True))
    op.add_column('bot_configs', sa.Column('transfer_amount', sa.Numeric(), nullable=True))
    op.add_column('bot_configs', sa.Column('auto_transfer_funds', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'auto_transfer_funds')
    op.drop_column('bot_configs', 'transfer_amount')
    op.drop_column('bot_configs', 'position_type')
    op.drop_column('bot_configs', 'custom_trailing_stop')
    op.drop_column('bot_configs', 'custom_take_profit')
    op.drop_column('bot_configs', 'custom_stop_loss')
    op.drop_column('bot_configs', 'custom_rsi_overbought')
    op.drop_column('bot_configs', 'custom_rsi_oversold')
    op.drop_column('bot_configs', 'custom_rsi_period')
    op.drop_column('bot_configs', 'custom_ema_slow')
    op.drop_column('bot_configs', 'custom_ema_fast')
    # ### end Alembic commands ###
