"""add strategy and ema_period to bot_config

Revision ID: 59a0e8d02f5a
Revises: 69694099e14e
Create Date: 2025-05-23 02:36:54.248355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a0e8d02f5a'
down_revision: Union[str, None] = '69694099e14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('strategy', sa.String(), nullable=False))
    op.add_column('bot_configs', sa.Column('ema_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_configs', 'ema_period')
    op.drop_column('bot_configs', 'strategy')
    # ### end Alembic commands ###
