"""add api_key_id to bot_config

Revision ID: 69694099e14e
Revises: 7354d6bd11ea
Create Date: 2025-05-23 02:32:36.984288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69694099e14e'
down_revision: Union[str, None] = '7354d6bd11ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configs', sa.Column('api_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bot_configs', 'api_keys', ['api_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot_configs', type_='foreignkey')
    op.drop_column('bot_configs', 'api_key_id')
    # ### end Alembic commands ###
