"""create_trade_table

Revision ID: 7354d6bd11ea
Revises: e2cbe40c4a2c
Create Date: 2025-05-23 02:17:16.226635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7354d6bd11ea'
down_revision: Union[str, None] = 'e2cbe40c4a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_config_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('binance_order_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('quantity_filled', sa.Numeric(), nullable=False),
    sa.Column('quote_quantity_filled', sa.Numeric(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(), nullable=True),
    sa.Column('commission_asset', sa.String(), nullable=True),
    sa.Column('pnl', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_config_id'], ['bot_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binance_order_id')
    )
    op.create_index(op.f('ix_trades_bot_config_id'), 'trades', ['bot_config_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_bot_config_id'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
