"""add realized_pnl to trade

Revision ID: 92c67f02186c
Revises: 59a0e8d02f5a
Create Date: 2025-05-23 02:43:54.738135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c67f02186c'
down_revision: Union[str, None] = '59a0e8d02f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('realized_pnl', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'realized_pnl')
    # ### end Alembic commands ###
