"""create_bot_state_table

Revision ID: e2cbe40c4a2c
Revises: 19adfce0d2a6
Create Date: 2025-05-23 02:08:18.501208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cbe40c4a2c'
down_revision: Union[str, None] = '19adfce0d2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('in_position', sa.Boolean(), nullable=True),
    sa.Column('entry_price', sa.Numeric(), nullable=True),
    sa.Column('current_position_size_coins', sa.Numeric(), nullable=True),
    sa.Column('trailing_stop_price', sa.Numeric(), nullable=True),
    sa.Column('max_price_since_entry', sa.Numeric(), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(), nullable=True),
    sa.Column('daily_trades_count', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['bot_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_states')
    # ### end Alembic commands ###
