name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (basic import check)
        run: |
          python -c "import sys; import pkgutil; sys.exit(0)"
      - name: Run tests
        env:
          DATABASE_URL: sqlite+aiosqlite:///./test.db
          SECRET_KEY: test_secret
          FERNET_KEY: dGVzdGZlcm5ldGZlcm5ldGZlcm5ldGZlcm5ldGZlcm5ldGZlcm5ldGZs
        run: |
          pytest -q

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Build
        env:
          VITE_API_URL: http://localhost:8000
        run: npm run build
